/**
 * Define a set of template paths to pre-load
 * Pre-loaded templates are compiled and cached for fast access when rendering
 * @return {Promise}
 */
export const preloadHandlebarsTemplates = async function () {
  return loadTemplates([
    'systems/demonlord-godless/templates/tabs/activeeffects.hbs',
    'systems/demonlord-godless/templates/tabs/afflictions.hbs',
    'systems/demonlord-godless/templates/tabs/background.hbs',
    'systems/demonlord-godless/templates/tabs/character.hbs',
    'systems/demonlord-godless/templates/tabs/combat.hbs',
    'systems/demonlord-godless/templates/tabs/creature-view.hbs',
    'systems/demonlord-godless/templates/tabs/creature-reference.hbs',
    'systems/demonlord-godless/templates/tabs/vehicle-view.hbs',
    'systems/demonlord-godless/templates/tabs/vehicle-reference.hbs',
    'systems/demonlord-godless/templates/tabs/creatureeffects.hbs',
    'systems/demonlord-godless/templates/tabs/effects.hbs',
    'systems/demonlord-godless/templates/tabs/effectsoverview.hbs',
    'systems/demonlord-godless/templates/tabs/item.hbs',
    'systems/demonlord-godless/templates/tabs/magic.hbs',
    'systems/demonlord-godless/templates/tabs/talents.hbs',
    'systems/demonlord-godless/templates/chat/challenge.hbs',
    'systems/demonlord-godless/templates/chat/combat.hbs',
    'systems/demonlord-godless/templates/chat/corruption.hbs',
    'systems/demonlord-godless/templates/chat/damage.hbs',
    'systems/demonlord-godless/templates/chat/description.hbs',
    'systems/demonlord-godless/templates/chat/heal.hbs',
    'systems/demonlord-godless/templates/chat/init.hbs',
    'systems/demonlord-godless/templates/chat/makechallengeroll.hbs',
    'systems/demonlord-godless/templates/chat/makeinitroll.hbs',
    'systems/demonlord-godless/templates/chat/rest.hbs',
    'systems/demonlord-godless/templates/chat/showtalent.hbs',
    'systems/demonlord-godless/templates/chat/spell.hbs',
    'systems/demonlord-godless/templates/chat/talent.hbs',
    'systems/demonlord-godless/templates/chat/useitem.hbs',
    'systems/demonlord-godless/templates/chat/formulaeroll.hbs',
    'systems/demonlord-godless/templates/actor/actor-sheet.hbs',
    'systems/demonlord-godless/templates/actor/limited-sheet.hbs',
    'systems/demonlord-godless/templates/actor/sidemenu.hbs',
    'systems/demonlord-godless/templates/actor/limited-sidemenu.hbs',
    'systems/demonlord-godless/templates/actor/header.hbs',
    'systems/demonlord-godless/templates/actor/limited-header.hbs',
    'systems/demonlord-godless/templates/dialogs/choose-turn-dialog.hbs',
    'systems/demonlord-godless/templates/dialogs/endofround-dialog.hbs',

    // Actor sheets
    'systems/demonlord-godless/templates/actor/creature-sheet.hbs',
    'systems/demonlord-godless/templates/actor/creature-header.hbs',
    'systems/demonlord-godless/templates/actor/creature-sidemenu.hbs',
    'systems/demonlord-godless/templates/actor/vehicle-sheet.hbs',
    'systems/demonlord-godless/templates/actor/vehicle-header.hbs',
    'systems/demonlord-godless/templates/actor/vehicle-sidemenu.hbs',

    // General templates
    'systems/demonlord-godless/templates/item/active-effect-config.hbs',
    'systems/demonlord-godless/templates/generic/tab-navigation.hbs',

    // Item Sheet Partials
    'systems/demonlord-godless/templates/item/partial/item-activation.hbs',
    'systems/demonlord-godless/templates/item/partial/item-contents.hbs',
    'systems/demonlord-godless/templates/item/partial/item-attacks.hbs',
    'systems/demonlord-godless/templates/item/partial/item-challenge.hbs',
    'systems/demonlord-godless/templates/item/partial/item-healing.hbs',
    'systems/demonlord-godless/templates/item/partial/item-measured-template.hbs',
    'systems/demonlord-godless/templates/item/partial/item-availability.hbs',
    'systems/demonlord-godless/templates/item/partial/item-description.hbs',
    
    // Item Sheets
    'systems/demonlord-godless/templates/item/parts/item-sheet-header.hbs',
    'systems/demonlord-godless/templates/item/parts/item-description.hbs',
    'systems/demonlord-godless/templates/item/parts/item-effects.hbs',
    'systems/demonlord-godless/templates/item/item-ancestry-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-ancestry-edit.hbs',
    'systems/demonlord-godless/templates/item/item-ancestry-view.hbs',  
    'systems/demonlord-godless/templates/item/item-ammo-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-armor-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-role-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-endoftheround-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-feature-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-item-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-language-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-path-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-path-edit.hbs',
    'systems/demonlord-godless/templates/item/item-path-view.hbs',
    'systems/demonlord-godless/templates/item/item-profession-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-relic-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-role-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-role-edit.hbs',
    'systems/demonlord-godless/templates/item/item-role-view.hbs',
    'systems/demonlord-godless/templates/item/item-specialaction-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-spell-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-talent-sheet.hbs',
    'systems/demonlord-godless/templates/item/item-weapon-sheet.hbs',

    // Chat Partials
    'systems/demonlord-godless/templates/chat/partial/chat-challenge.hbs',
    'systems/demonlord-godless/templates/chat/partial/chat-attack.hbs',
    'systems/demonlord-godless/templates/chat/partial/chat-damage.hbs',
    'systems/demonlord-godless/templates/chat/partial/chat-measured-template.hbs',
    'systems/demonlord-godless/templates/chat/partial/chat-effects.hbs',
    'systems/demonlord-godless/templates/chat/partial/chat-description.hbs',
    "systems/demonlord-godless/templates/chat/partial/chat-extra-effects.hbs",
  ])
}
